### ISSUE TITLE
请问支持多页签缓存吗？

### ISSUE THREAD

**Issue by wenjie79** [lishaobos/vite-plugin-legacy-qiankun#1]

**Comment by lishaobos** [comment]
可以详细描述下吗？

**Comment by wenjie79** [comment]
同时打开同一个子应用的多个页面，是否能够做到沙箱隔离呢？

**Comment by lishaobos** [comment]
老兄，我没 get 到你的点，我这个插件做的就是让 vite 项目 js，css 可以被 qiankun 拦截，被拦截了也就会有js，css 沙箱，所以只要 qiankun 原本支持，就支持，没有就没有了😂😂😂

**Comment by wenjie79** [comment]
好的，谢谢你的回复

**Comment by lishaobos** [comment]
没事，交流交流
