### ISSUE TITLE
主应用访问子应用报'import.meta' outside a module

### ISSUE THREAD

**Issue by qimingzizeinan** [lishaobos/vite-plugin-legacy-qiankun#12]
主应用和子应用都是jeecg这个开源项目，都是vue3 + vite。子应用中用了vite-plugin-legacy-qiankun插件。但是我在主应用中访问子应用会报SyntaxError: Cannot use 'import.meta' outside a module这个错误。请问有遇到过或者有什么解决方法么？

**Comment by lishaobos** [comment]
可以先检查下 vite 版本是否 >= 3，然后看下配置有问题没

参考这个 https://github.com/lishaobos/vite-plugin-legacy-qiankun/issues/8 ，也是 jeecg 项目，我跑起来没问题

**Comment by lishaobos** [comment]
如果还不能解决，那就麻烦提供一个可复现的 git 仓库，我看下

**Comment by qimingzizeinan** [comment]
我自己搞定了。感谢大佬写的插件，救我狗命。

**Comment by lishaobos** [comment]
> 我自己搞定了。感谢大佬写的插件，救我狗命。

ok，搞定就好.
