### ISSUE TITLE
在TS中按照示例进行配置，有类型错误。

### ISSUE THREAD

**Issue by Onedim941** [lishaobos/vite-plugin-legacy-qiankun#2]
问题：在TS环境中按照示例进行配置，legacyQiankun报类型错误。
版本:  -React : 18.2.0
          -Vite: 4.1.4
          -Vite-plugin-legacy-qiankun: 0.0.2
          -Typescript: 4.9.3
![image](https://user-images.githubusercontent.com/83023380/221078526-072eb07d-a2de-46a6-956e-c053edafa428.png)
复现：https://stackblitz.com/edit/vitejs-vite-snsyq5?file=vite.config.ts&terminal=dev

**Comment by lishaobos** [comment]
> 问题：在TS环境中按照示例进行配置，legacyQiankun报类型错误。 版本: -React : 18.2.0 -Vite: 4.1.4 -Vite-plugin-legacy-qiankun: 0.0.2 -Typescript: 4.9.3 ![image](https://user-images.githubusercontent.com/83023380/221078526-072eb07d-a2de-46a6-956e-c053edafa428.png) 复现：https://stackblitz.com/edit/vitejs-vite-snsyq5?file=vite.config.ts&terminal=dev

哥们，更新下版本 0.0.3
