### ISSUE TITLE
首次调用loadMicroApp Url会自动切换成子应用url

### ISSUE THREAD

**Issue by CTzhida** [lishaobos/vite-plugin-legacy-qiankun#3]
![企业微信截图_cc0394b4-60ae-4a46-8f17-ed51a77e3150](https://user-images.githubusercontent.com/30852299/222062598-d3194fe0-7c96-40cd-b29b-529177c5c057.png)
![企业微信截图_cbe9445f-50e7-439b-b323-2af3f3559c0c](https://user-images.githubusercontent.com/30852299/222062636-43049f4f-ed4b-40ef-9800-a7c136e6fcaa.png)
![企业微信截图_69db4778-1a03-4b42-b94a-c097ce2b033b](https://user-images.githubusercontent.com/30852299/222062641-99b53acb-deb8-4669-b7e7-1e6c063b1712.png)

**Comment by CTzhida** [comment]
先进入子应用vite_vue2 点击按钮去手动加载vite_vue3 浏览器的url自动切换到/vite_vue3

**Comment by lishaobos** [comment]
> 先进入子应用vite_vue2 点击按钮去手动加载vite_vue3 浏览器的url自动切换到/vite_vue3

这是 vue-router@4 的一个 bug 或者设计，你可以先采用以下建议：

```js
// 主应用通过 url 变化加载子应用
const router = createRouter({
  history: createWebHistory(microApp.__POWERED_BY_QIANKUN__ ? pkg.name : '/')
})
```

```js
// 主应用通过 loadMicroApp 加载子应用
const router = createRouter({
  // history: createWebHistory(microApp.__POWERED_BY_QIANKUN__ ? pkg.name : '/')
})
```

**Comment by CTzhida** [comment]
> 



> > 先进入子应用vite_vue2 点击按钮去手动加载vite_vue3 浏览器的url自动切换到/vite_vue3
> 
> 这是 vue-router@4 的一个 bug 或者设计，你可以先采用以下建议：
> 
> ```js
> // 主应用通过 url 变化加载子应用
> const router = createRouter({
>   history: createWebHistory(microApp.__POWERED_BY_QIANKUN__ ? pkg.name : '/')
> })
> ```
> 
> ```js
> // 主应用通过 loadMicroApp 加载子应用
> const router = createRouter({
>   history: createWebHistory('/')
> })
> ```

谢谢大佬，试过之后可以了
