### ISSUE TITLE
pkg.name含有空格或横线时会报错

### ISSUE THREAD

**Issue by Lycreal** [lishaobos/vite-plugin-legacy-qiankun#6]
```ts
// vite.config.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue2'
import legacy from '@vitejs/plugin-legacy' // need this
import { legacyQiankun } from 'vite-plugin-legacy-qiankun'

export default defineConfig({
  ...
  plugins: [
    vue(),
    legacy(),
    legacyQiankun({ name: 'your micro app name' })
  ],
  ...
}
```
开发环境报错：
![image](https://user-images.githubusercontent.com/15781426/232389586-668b62a7-b4e2-4360-a3c8-a228ae9cd0ea.png)

**Comment by lishaobos** [comment]
> ```ts
> // vite.config.ts
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue2'
> import legacy from '@vitejs/plugin-legacy' // need this
> import { legacyQiankun } from 'vite-plugin-legacy-qiankun'
> 
> export default defineConfig({
>   ...
>   plugins: [
>     vue(),
>     legacy(),
>     legacyQiankun({ name: 'your micro app name' })
>   ],
>   ...
> }
> ```
> 
> 开发环境报错： ![image](https://user-images.githubusercontent.com/15781426/232389586-668b62a7-b4e2-4360-a3c8-a228ae9cd0ea.png)

试一下 0.0.8 版本，不确定是否是同一个原因导致

**Comment by Lycreal** [comment]
已解决，感谢

**Comment by lishaobos** [comment]
> 已解决，感谢

么事，好了就行
